version: '2'

services:
   dokuwiki:
     image: johanneselias/dokuwiki-backup
     volumes: 
       - ./backups:/backups
     ports:
       - "80:80"
     restart: always
     environment:
       DOKUWIKI_SUB_DIR: dok
       DOKUWIKI_BACKUP_SCHEDULE: "0 0 * * *"

